### ISSUE TITLE
Toad Protector Server Crash

### ISSUE THREAD

**Issue by WenXin20** [itsmeowCommissions/ToadTerror#3]
**Describe what you were doing before the crash**
A toad protector had been summon using the summon command while testing. There was also an iron golem nearby.
.
**To Reproduce**
1. Summon the Toad Protector
2. Server Crashes a few minutes later.

**Crash Log**
[Crash Report](https://gist.github.com/WenXin20/acc7dbe051622d4f26936c66bc915055)

**Versions:**
 - `Minecraft v1.16.5`
 - `Forge v36.1.24`
 - `Toad Terror v1.0.0`

**Comment by itsmeow** [comment]
Don't spawn it with the summon command. It is tied to the gem, and without a gem, the toad protector has undefined behavior.

**Comment by WenXin20** [comment]
Ah thanks
